set-option -ga terminal-overrides ",xterm-256color:Tc"
set -g default-terminal "screen-256color"

# Use Ctrl-a as prefix
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# Binds for splits
unbind %
unbind '"'
bind | split-window -h
bind - split-window -v

# Bind r to reload configuration
unbind r
bind r source-file ~/.tmux.conf

# Bindings to resize panes
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

set -g mouse on

# Status bar at the top
set -g status-position top

# Start counting at 1
set -g base-index 1
setw -g pane-base-index 1

# Plugins
set -g @plugin 'tmux-plugin/tpm'

# List of tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'jimeh/tmux-themepack'

set -g @themepack 'powerline/block/cyan'

# Initialize TMUX plugin manager (keep this line at the end of .tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
