[[items]]
file = "~/.alacritty.yml"
template = "alacritty"

[[items]]
file = "~/.config/rofi/theme.rasi"
template = "rofi"
rewrite = true

[[items]]
file = "~/.vim/base16theme"
template = "vim"
rewrite = true
